
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 28 21:33:12 CDT 2016
//----------------------------------------------------

package SMTParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EXISTS = 6;
  public static final int SYMBOL = 10;
  public static final int TK_LEFTPAREN = 3;
  public static final int EOF = 0;
  public static final int TK_UNDERSCORE = 9;
  public static final int NUMERAL = 11;
  public static final int TK_RIGHTPAREN = 4;
  public static final int error = 1;
  public static final int LEFTPAREN = 8;
  public static final int RIGHTPAREN = 7;
  public static final int TK_DEFINE_FUN = 2;
  public static final int TK_FORALL = 5;
}

