
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 22 19:29:50 CDT 2016
//----------------------------------------------------

package smtparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EXISTS = 4;
  public static final int BVCONSTANT = 12;
  public static final int SYMBOL = 8;
  public static final int BINCONSTANT = 10;
  public static final int RATCONSTANT = 13;
  public static final int EOF = 0;
  public static final int HEXCONSTANT = 11;
  public static final int TK_UNDERSCORE = 7;
  public static final int NUMERAL = 9;
  public static final int error = 1;
  public static final int LEFTPAREN = 6;
  public static final int RIGHTPAREN = 5;
  public static final int TK_DEFINE_FUN = 2;
  public static final int TK_FORALL = 3;
}

