
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 14 00:13:57 CDT 2016
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 5;
  public static final int RPAREN = 4;
  public static final int DEFINE = 9;
  public static final int INT = 12;
  public static final int CHAR = 15;
  public static final int CONCAT = 10;
  public static final int FUNCTION = 2;
  public static final int MAPTO = 7;
  public static final int LPAREN = 3;
  public static final int COLON = 8;
  public static final int ID = 22;
  public static final int WITH = 16;
  public static final int OUTPUTFUNCTION = 24;
  public static final int EOF = 0;
  public static final int WHEN = 19;
  public static final int BV = 14;
  public static final int error = 1;
  public static final int PREDICATE = 23;
  public static final int DECLARATION = 21;
  public static final int BOOL = 13;
  public static final int APPEND = 11;
  public static final int VLINE = 6;
  public static final int INTVALUE = 20;
  public static final int MATCH = 18;
  public static final int INVERT = 17;
}

